### ISSUE TITLE
Run migration For all non-ftree entities

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/beit-hatfutsot-devops#14]
Currently there are updates to content on BHP that we do not yet display.
We need to run migration manually for all non-ftree items we do not yet have the latest versions for.

Verify:
http://dbs.bh.org.il/he/%D7%A6%D7%A8%D7%A0%D7%99-%D7%9C%D7%90%D7%95%D7%9F-%D7%94%D7%90%D7%A8%D7%99%D7%A1/%D7%90%D7%99%D7%A9%D7%99%D7%95%D7%AA

 צ'רני, לאון האריס 
will be replaced with
 צ'ארניי, לאון האריס

**Comment by OriHoch** [comment]
fixed for the [item in the description](http://dbs.bh.org.il/he/%D7%A6%D7%A8%D7%A0%D7%99-%D7%9C%D7%90%D7%95%D7%9F-%D7%94%D7%90%D7%A8%D7%99%D7%A1/%D7%90%D7%99%D7%A9%D7%99%D7%95%D7%AA), but migration is still running, will close issue when it's done

**Comment by OriHoch** [comment]
done
