### ISSUE TITLE
API should only allow access to items with full internet rights

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/beit-hatfutsot-devops#22]
@nuritgazit commented on [Tue May 16 2017](https://github.com/Beit-Hatfutsot/dbs-front/issues/381)

the item 26559 from BHP, that has no internet rights, and does not appear on the DBs site (which is good), does appear in search results on CJH (which is not good)

**Comment by OriHoch** [comment]
to the best of my knowledge, currently after many fixes and improvements over the past months API only shows items with full rights

**Comment by OriHoch** [comment]
I don't see what actionable task I have here, assigning to @TheGrandVizier

**Comment by TheGrandVizier** [comment]
If there was a problem here, it is fixed now.
I have taken a few random samples that are all Rights = None and non of them produced results in either our general search nor on cjh.org.
I think Ori is right and the issue was already fixed indirectly by API upgrades.

Closing.
