### ISSUE TITLE
Set up remote desktop tool on Instagram PC

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/beit-hatfutsot-devops#5]
In order to have the ability to control the instagram computer from the office, we need to set up a remote desktop connection.
Windows has remote desktop built in, so only setup is required.

@nuritgazit  we should be able to do this without involving Mr Madmon.

**Comment by OriHoch** [comment]
Some more options - 
http://www.tightvnc.com/
https://www.nomachine.com/

**Comment by TheGrandVizier** [comment]
sorted
