### ISSUE TITLE
Write an Admin Guide

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/beit-hatfutsot-devops#9]
Summarize all the requests we got from editors and users that were handled by a sysadmin and write a guide covering the common scenarios.

**Comment by nuritgazit** [comment]
@daonb @TheGrandVizier This is done, right?
Can we get the links to the document/s and then close it?

**Comment by OriHoch** [comment]
https://github.com/Beit-Hatfutsot/dbs-back/blob/dev/docs/admin.md

**Comment by OriHoch** [comment]
thanks @daonb !
